baseURL = "https://taitootsu-timba.github.io/nikki/"
languageCode = "ja"
title = "Preparando..."
theme = "ananke"

[params]
customCSS = ["css/style.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
