baseURL = "https://taitootsu-timba.github.io/nikki/"
relativeURLs = false
languageCode = "ja"
title = "Preparando..."
theme = "ananke"
uglyURLs = false
canonifyURLs = true

[params]
  custom_css = ["css/style.css"]
  mainSections = ["posts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/posts/:filename/"
