name: Hugo Deploy

on:
  push:
    branches:
      - main  # main ブランチに push されたときに動く

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Hugo セットアップ
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.155.3'  # あなたの Hugo バージョンに合わせる

      - name: Hugo ビルド
        run: hugo --minify

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
